import AutoComplete from 'primevue/autocomplete';
import Breadcrumb from 'primevue/breadcrumb';
import Button from 'primevue/button';
import Calendar from 'primevue/calendar';
import Card from 'primevue/card';
import Column from 'primevue/column';
import PrimeVue from 'primevue/config';
import ConfirmationService from 'primevue/confirmationservice';
import ConfirmDialog from 'primevue/confirmdialog';
import DataTable from 'primevue/datatable';
import Dialog from 'primevue/dialog';
import Divider from 'primevue/divider';
import Dropdown from 'primevue/dropdown';
import Image from 'primevue/image';
import InputSwitch from 'primevue/inputswitch';
import Input from 'primevue/inputtext';
import Knob from 'primevue/knob';
import Menu from 'primevue/menu';
import Message from 'primevue/message';
import MultiSelect from 'primevue/multiselect';
import Password from 'primevue/password';
import Rating from 'primevue/rating';
import Ripple from 'primevue/ripple';
import ScrollTop from 'primevue/scrolltop';
import SelectButton from 'primevue/selectbutton';
import Tag from 'primevue/tag';
import Textarea from 'primevue/textarea';
import Toast from 'primevue/toast';
import OrganizationChart from 'primevue/organizationchart';
import ToastService from 'primevue/toastservice';
import Tooltip from 'primevue/tooltip';
import Chips from 'primevue/chips';

import {defineNuxtPlugin} from '#imports';

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(PrimeVue, {
    ripple: true,
  });
  nuxtApp.vueApp.use(ToastService);
  nuxtApp.vueApp.use(ConfirmationService);
  nuxtApp.vueApp.directive('ripple', Ripple);
  nuxtApp.vueApp.directive('tooltip', Tooltip);
  nuxtApp.vueApp.component('Chips', Chips);
  nuxtApp.vueApp.component('Toast', Toast);
  nuxtApp.vueApp.component('OrganizationChart', OrganizationChart);
  nuxtApp.vueApp.component('Button', Button);
  nuxtApp.vueApp.component('Card', Card);
  nuxtApp.vueApp.component('Knob', Knob);
  nuxtApp.vueApp.component('Image', Image);
  nuxtApp.vueApp.component('MultiSelect', MultiSelect);
  nuxtApp.vueApp.component('Dropdown', Dropdown);
  nuxtApp.vueApp.component('Message', Message);
  nuxtApp.vueApp.component('Textarea', Textarea);
  nuxtApp.vueApp.component('InputSwitch', InputSwitch);
  nuxtApp.vueApp.component('Rating', Rating);
  nuxtApp.vueApp.component('Input', Input);
  nuxtApp.vueApp.component('Password', Password);
  nuxtApp.vueApp.component('Divider', Divider);
  nuxtApp.vueApp.component('ScrollTop', ScrollTop);
  nuxtApp.vueApp.component('ConfirmDialog', ConfirmDialog);
  nuxtApp.vueApp.component('Dialog', Dialog);
  nuxtApp.vueApp.component('Menu', Menu);
  nuxtApp.vueApp.component('SelectButton', SelectButton);
  nuxtApp.vueApp.component('DataTable', DataTable);
  nuxtApp.vueApp.component('Column', Column);
  nuxtApp.vueApp.component('Tag', Tag);
  nuxtApp.vueApp.component('Calendar', Calendar);
  nuxtApp.vueApp.component('AutoComplete', AutoComplete);
  nuxtApp.vueApp.component('Breadcrumb', Breadcrumb);
});
