name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-client:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish client
        run: |
          docker build . --tag ghcr.io/alexbidenko1998/cyber-garden-16-frontend/client:latest
          docker push ghcr.io/alexbidenko1998/cyber-garden-16-frontend/client:latest

  build-nginx:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish nginx
        run: |
          docker build nginx --tag ghcr.io/alexbidenko1998/cyber-garden-16-frontend/nginx:latest
          docker push ghcr.io/alexbidenko1998/cyber-garden-16-frontend/nginx:latest

  deploy:
    runs-on: ubuntu-22.04

    needs: [build-client, build-nginx]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh/
          ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy 🚀
        run: docker stack deploy --prune --with-registry-auth -c docker-compose.yml asmy-site
        env:
          DOCKER_HOST: ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
